In [1]:
# 导入模块
import sys
import numpy as np
import pandas as pd
from pathlib import Path
sys.path.append("..")
from utils.set_fonts import apply_times_with_cn
en_fp, cn_fp = apply_times_with_cn(cn_font_path=r"C:\Windows\\Fonts\\msyh.ttc")

Applied font.family: ['Times New Roman', 'Microsoft YaHei', 'DejaVu Sans']
findfont Times -> C:\Windows\Fonts\times.ttf
findfont CN -> C:\Windows\\Fonts\\msyh.ttc

In [ ]:
from utils.common import get_train_and_test_pos, get_gens
from evaluation.fidelity import marginal_fidelity

num_cols = ["Age"]
cat_cols = ["Gender", "Polyuria", "Polydipsia", "sudden weight loss", 
            "weakness", "Polyphagia", "Genital thrush", "visual blurring", 
            "Itching", "Irritability", "delayed healing", "partial paresis", 
            "muscle stiffness", "Alopecia", "Obesity"]

dataset_name = "diabetes_risk_prediction"
seed = 42
fold = 1

In [ ]:
train_pos, test_pos = get_train_and_test_pos(dataset_name, seed, fold)
none_noft = get_gens(dataset_name, seed, fold, "none_noft", "fidelity")
none_ft = get_gens(dataset_name, seed, fold, "none_ft", "fidelity")

tabkde = get_gens(dataset_name, seed, fold, "tabkde", "fidelity")

print(marginal_fidelity(train_pos, none_noft,  num_cols=num_cols, cat_cols=cat_cols))
print(marginal_fidelity(train_pos, none_ft,  num_cols=num_cols, cat_cols=cat_cols))

{'Age': 0.8663594470046083, 'Gender': 0.9308755760368663, 'Polyuria': 0.9677419354838709, 'Polydipsia': 0.9216589861751152, 'sudden weight loss': 0.9631336405529954, 'weakness': 0.9216589861751152, 'Polyphagia': 0.9953917050691244, 'Genital thrush': 0.9815668202764977, 'visual blurring': 0.9953917050691243, 'Itching': 0.9861751152073733, 'Irritability': 0.880184331797235, 'delayed healing': 0.9539170506912442, 'partial paresis': 0.9815668202764977, 'muscle stiffness': 0.9815668202764977, 'Alopecia': 0.9907834101382489, 'Obesity': 0.9032258064516129, '__num_avg__': 0.8663594470046083, '__cat_avg__': 0.956989247311828, '__overall__': 0.9513248847926268}
{'Age': 0.9124423963133641, 'Gender': 0.9631336405529954, 'Polyuria': 0.9677419354838709, 'Polydipsia': 0.9769585253456221, 'sudden weight loss': 0.9400921658986175, 'weakness': 0.9216589861751152, 'Polyphagia': 0.9447004608294931, 'Genital thrush': 0.9493087557603687, 'visual blurring': 1.0, 'Itching': 0.9585253456221198, 'Irritability': 0.9769585253456221, 'delayed healing': 0.9953917050691244, 'partial paresis': 0.9815668202764977, 'muscle stiffness': 0.9585253456221198, 'Alopecia': 0.9861751152073732, 'Obesity': 0.8986175115207373, '__num_avg__': 0.9124423963133641, '__cat_avg__': 0.9612903225806452, '__overall__': 0.9582373271889401}

In [29]:
tabkde = get_gens("diabetes_risk_prediction", 42, 1, "tabkde", "fidelity")
marginal_fidelity(train_pos, tabkde, 
                  num_cols=["Age"],
                  cat_cols=["Gender", "Polyuria", "Polydipsia", "sudden weight loss", 
                            "weakness", "Polyphagia", "Genital thrush", "visual blurring", 
                            "Itching", "Irritability", "delayed healing", "partial paresis", 
                            "muscle stiffness", "Alopecia", "Obesity"])

{'Age': 0.9585253456221198,
 'Gender': 0.9861751152073732,
 'Polyuria': 0.9493087557603687,
 'Polydipsia': 0.9861751152073733,
 'sudden weight loss': 0.9539170506912442,
 'weakness': 0.967741935483871,
 'Polyphagia': 0.9493087557603687,
 'Genital thrush': 1.0,
 'visual blurring': 1.0,
 'Itching': 0.9493087557603687,
 'Irritability': 0.9861751152073732,
 'delayed healing': 0.9815668202764977,
 'partial paresis': 0.9907834101382489,
 'muscle stiffness': 0.9400921658986174,
 'Alopecia': 0.9723502304147464,
 'Obesity': 0.9631336405529954,
 '__num_avg__': 0.9585253456221198,
 '__cat_avg__': 0.9717357910906298,
 '__overall__': 0.970910138248848}

In [3]:
from utils.common import get_per_fold_result

get_per_fold_result("breast_cancer_coimbra", 42, 2)

,Method,Dataset,Seed,Fold,Classifier,Recall,F1_score,G_mean
0,raw,breast_cancer_coimbra,42,2,SVC,0.636364,0.666667,0.641689
1,raw,breast_cancer_coimbra,42,2,MLP,0.681818,0.652174,0.566441
2,raw,breast_cancer_coimbra,42,2,XGB,0.636364,0.666667,0.641689
3,smote,breast_cancer_coimbra,42,2,SVC,0.681818,0.681818,0.633300
4,smote,breast_cancer_coimbra,42,2,MLP,0.954545,0.724138,0.335111
5,smote,breast_cancer_coimbra,42,2,XGB,0.863636,0.760000,0.637509
6,ctgan,breast_cancer_coimbra,42,2,SVC,0.500000,0.564103,0.568796
7,ctgan,breast_cancer_coimbra,42,2,MLP,0.772727,0.641509,0.369274
8,ctgan,breast_cancer_coimbra,42,2,XGB,0.818182,0.720000,0.580429
9,tvae,breast_cancer_coimbra,42,2,SVC,0.590909,0.604651,0.559316
10,tvae,breast_cancer_coimbra,42,2,MLP,0.772727,0.680000,0.522233
11,tvae,breast_cancer_coimbra,42,2,XGB,0.681818,0.652174,0.566441
12,forestdiffusion,breast_cancer_coimbra,42,2,SVC,0.318182,0.378378,0.410426
13,forestdiffusion,breast_cancer_coimbra,42,2,MLP,0.909091,0.727273,0.462497
14,forestdiffusion,breast_cancer_coimbra,42,2,XGB,0.772727,0.708333,0.603023
15,tabddpm,breast_cancer_coimbra,42,2,SVC,0.500000,0.594595,0.618347
16,tabddpm,breast_cancer_coimbra,42,2,MLP,0.818182,0.666667,0.379980
17,tabddpm,breast_cancer_coimbra,42,2,XGB,0.727273,0.695652,0.620505
18,tabkde,breast_cancer_coimbra,42,2,SVC,0.590909,0.634146,0.618347
19,tabkde,breast_cancer_coimbra,42,2,MLP,1.000000,0.745763,0.342997
20,tabkde,breast_cancer_coimbra,42,2,XGB,0.818182,0.734694,0.620505
21,none_noft,breast_cancer_coimbra,42,2,SVC,0.636364,0.682927,0.670222
22,none_noft,breast_cancer_coimbra,42,2,MLP,0.772727,0.666667,0.476731
23,none_noft,breast_cancer_coimbra,42,2,XGB,0.636364,0.636364,0.580429
24,none_ft,breast_cancer_coimbra,42,2,SVC,0.636364,0.666667,0.641689
25,none_ft,breast_cancer_coimbra,42,2,MLP,0.818182,0.692308,0.490552
26,none_ft,breast_cancer_coimbra,42,2,XGB,0.636364,0.636364,0.580429
27,bootstrap_noft,breast_cancer_coimbra,42,2,SVC,0.636364,0.651163,0.611826
28,bootstrap_noft,breast_cancer_coimbra,42,2,MLP,0.772727,0.666667,0.476731
29,bootstrap_noft,breast_cancer_coimbra,42,2,XGB,0.681818,0.666667,0.600802
30,bootstrap_ft,breast_cancer_coimbra,42,2,SVC,0.636364,0.666667,0.641689
31,bootstrap_ft,breast_cancer_coimbra,42,2,MLP,0.772727,0.666667,0.476731
32,bootstrap_ft,breast_cancer_coimbra,42,2,XGB,0.772727,0.723404,0.639602
33,smote_noft,breast_cancer_coimbra,42,2,SVC,0.681818,0.666667,0.600802
34,smote_noft,breast_cancer_coimbra,42,2,MLP,0.772727,0.680000,0.522233
35,smote_noft,breast_cancer_coimbra,42,2,XGB,0.772727,0.723404,0.639602
36,smote_ft,breast_cancer_coimbra,42,2,SVC,0.636364,0.666667,0.641689
37,smote_ft,breast_cancer_coimbra,42,2,MLP,0.818182,0.679245,0.438763
38,smote_ft,breast_cancer_coimbra,42,2,XGB,0.727273,0.680851,0.585018

In [82]:
from result_analysis.load_results import load_dataset_long_table
from result_analysis.inner_dataset_analysis import (
    validate_and_prepare, parse_ifc_cells, descriptive_table,
    art_anova_summary_all_classifiers, method_rank_frequency
)

root = Path.cwd().parent
DATASETS = ['breast_cancer_coimbra', 'PIMA_diabetes','TCGA_InfoWithGrade', 'Thyroid_Diff',
            'diabetes_risk_prediction', 'framingham', 'hepatitis']
dataset_name = DATASETS[5]


df = load_dataset_long_table(root = root,  dataset=dataset_name)
df = validate_and_prepare(df, dataset=dataset_name)
df = parse_ifc_cells(df)

desc = descriptive_table(df, "Recall")

#sorted_rank = method_rank_frequency(df, "F1_score", "SVC")
#print(sorted_rank)

framingham 加载完成: 156行 = 1seed x 4fold(实际按block计) x 13method x 3classifier (注：若fold数因数据集样本量不同而变化，n_seed x n_fold 只是粗略参考)

In [83]:
desc

,Method,Classifier,n,mean,std,ci_low,ci_high,is_ifc_cell,rank
0,tabkde,MLP,4,0.582440,0.078514,0.521469,0.646394,False,1
1,tabddpm,MLP,4,0.555263,0.062583,0.501999,0.608527,False,2
2,none_ft,MLP,4,0.413548,0.053394,0.369731,0.457364,True,3
3,smote,MLP,4,0.398165,0.045866,0.356589,0.438681,False,4
4,none_noft,MLP,4,0.355423,0.036649,0.323643,0.386037,True,5
5,smote_noft,MLP,4,0.335907,0.046943,0.302961,0.381783,True,6
6,tvae,MLP,4,0.332092,0.035008,0.302326,0.361858,False,7
7,smote_ft,MLP,4,0.328155,0.053082,0.290698,0.375969,True,8
8,bootstrap_ft,MLP,4,0.320479,0.065330,0.267442,0.373516,True,9
9,bootstrap_noft,MLP,4,0.275875,0.088586,0.205426,0.346324,True,10
10,ctgan,MLP,4,0.188242,0.059516,0.145976,0.244186,False,11
11,forestdiffusion,MLP,4,0.126226,0.017312,0.108785,0.137597,False,12
12,raw,MLP,4,0.029070,0.040218,0.000000,0.063953,False,13
13,raw,SVC,4,0.679521,0.033812,0.647090,0.705426,False,1
14,tabkde,SVC,4,0.671754,0.032634,0.641231,0.693798,False,2
15,tvae,SVC,4,0.638793,0.023266,0.618671,0.658915,False,3
16,smote,SVC,4,0.578594,0.038330,0.555551,0.618217,False,4
17,tabddpm,SVC,4,0.572659,0.056674,0.522241,0.612403,False,5
18,none_noft,SVC,4,0.561062,0.047276,0.521348,0.600775,True,6
19,none_ft,SVC,4,0.555233,0.043320,0.520349,0.589147,True,7
20,smote_ft,SVC,4,0.553370,0.051526,0.511628,0.599882,True,8
21,smote_noft,SVC,4,0.537851,0.037347,0.505814,0.565891,True,9
22,bootstrap_noft,SVC,4,0.405932,0.060235,0.356589,0.455275,True,10
23,bootstrap_ft,SVC,4,0.405796,0.042719,0.374031,0.446493,True,11
24,ctgan,SVC,4,0.359042,0.082319,0.295603,0.424419,False,12
25,forestdiffusion,SVC,4,0.297042,0.064397,0.245246,0.348837,False,13
26,tabkde,XGB,4,0.664032,0.022299,0.645894,0.682171,False,1
27,none_noft,XGB,4,0.619383,0.022695,0.603107,0.639535,True,2
28,none_ft,XGB,4,0.596036,0.053446,0.561364,0.649225,True,3
29,smote,XGB,4,0.596006,0.040184,0.559336,0.624031,False,4
30,smote_ft,XGB,4,0.568920,0.074298,0.518532,0.639535,True,5
31,tabddpm,XGB,4,0.530099,0.043090,0.499092,0.569767,False,6
32,smote_noft,XGB,4,0.514505,0.064051,0.470870,0.574582,True,7
33,bootstrap_ft,XGB,4,0.437000,0.095946,0.355605,0.509660,True,8
34,bootstrap_noft,XGB,4,0.398301,0.123663,0.294574,0.502029,True,9
35,tvae,XGB,4,0.382570,0.112257,0.275981,0.474806,False,10
36,ctgan,XGB,4,0.244277,0.149956,0.122366,0.360465,False,11
37,forestdiffusion,XGB,4,0.102910,0.009710,0.095158,0.112403,False,12
38,raw,XGB,4,0.036852,0.021307,0.019440,0.054264,False,13

In [65]:
from utils.common import get_gens

kmeans_ft = get_gens("PIMA_diabetes", 42, 2, 'none_ft', 'fidelity')

kmeans_ft.describe().round(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
count,182.00,182.00,182.00,182.00,182.00,182.00,182.00,182.00
mean,4.87,130.84,70.25,24.16,14.99,32.92,0.36,35.85
std,3.75,19.40,19.65,14.73,45.10,5.29,0.18,8.22
min,0.00,74.00,0.00,0.00,0.00,0.00,0.09,21.00
25%,1.00,119.00,66.00,15.50,0.00,30.40,0.24,29.00
50%,5.00,129.00,74.00,29.00,0.00,32.80,0.32,38.00
75%,8.00,145.00,82.00,36.00,0.00,35.30,0.45,42.00
max,13.00,190.00,94.00,46.00,300.00,51.20,1.22,64.00

In [ ]:
import pandas as pd

df_real = fold_data.X_train_pos

def compare_single_column(df1, df2, col):
    """返回单列的对比表，索引为类别，列为两个数据集占比"""
    dist1 = df1[col].value_counts(normalize=True).mul(100).round(2)
    dist2 = df2[col].value_counts(normalize=True).mul(100).round(2)
    compare = pd.DataFrame({
        f'{col}_0': dist1,
        f'{col}_1': dist2
    }).fillna(0)
    return compare

# 假设你要对比的列名列表
cat_cols = fold_data.cat_cols

# 存储所有列的对比结果
compare_dict = {}
for col in cat_cols:
    compare_dict[col] = compare_single_column(df_real, X_syn, col)

# 你可以单独查看某一列：
for col in cat_cols:
    print(compare_dict[col])